eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/         #注册中心的访问地址
  instance:
    prefer-ip-address: true                   #是否将当前服务ip注册到server



server:
  port: 8010
spring:
  application:
    name: provodier